debug: true
spring:
  sql:
    init:
      platform: postgresql
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnesstracker
    username: pguser
    password: pgpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

